//Autogenerated file using USB4ALL Descriptor generator V1.0  Author: Rafael Fernandez

#ifndef USBMMAP_H
#define USBMMAP_H
// I N C L U D E S **********************************************************

#include <xc.h>		//sino no encontraba el UEP1
#include "system/typedefs.h"
#include "usb4all/boot/boot.h" //mia
// D E F I N I T I O N S ****************************************************

//Buffer Descriptor Status Register Initialization Parameters
#define _BSTALL     0x04                //Buffer Stall enable
#define _DTSEN      0x08                //Data Toggle Synch enable
#define _INCDIS     0x10                //Address increment disable
#define _KEN        0x20                //SIE keeps buff descriptors enable
#define _DAT0       0x00                //DATA0 packet expected next
#define _DAT1       0x40                //DATA1 packet expected next
#define _DTSMASK    0x40                //DTS Mask
#define _USIE       0x80                //SIE owns buffer
#define _UCPU       0x00                //CPU owns buffer

//USB Device States - To be used with [byte usb_device_state]
#define DETACHED_STATE       (byte) 0
#define ATTACHED_STATE       (byte) 1
#define POWERED_STATE        (byte) 2
#define DEFAULT_STATE        (byte) 3
#define ADR_PENDING_STATE    (byte) 4
#define ADDRESS_STATE        (byte) 5
#define CONFIGURED_STATE     (byte) 6

//		tamaño de los endpoints(va a quedar deprecated)

#define USBGEN_EP_SIZE   64
#define MAX_EP_NUMBER     1         // max nro de endpoints

//Memory Types for Control Transfer - used in USB_DEVICE_STATUS

#define _RAM (unsigned) 0
#define _ROM (unsigned) 1

// T Y P E S ****************************************************************

typedef union _USB_DEVICE_STATUS
{
    byte _byte;
    struct
    {
        unsigned char RemoteWakeup:1;// [0]Disabled [1]Enabled: See usbdrv.c,usb9.c
        unsigned char ctrl_trf_mem:1;// [0]RAM      [1]ROM
    };
} USB_DEVICE_STATUS;

typedef union _BD_STAT
{
    byte _byte;
    struct{
        unsigned char BC8:1;
        unsigned char BC9:1;
        unsigned char BSTALL:1;              //Buffer Stall Enable
        unsigned char DTSEN:1;               //Data Toggle Synch Enable
        unsigned char INCDIS:1;              //Address Increment Disable
        unsigned char KEN:1;                 //BD Keep Enable
        unsigned char DTS:1;                 //Data Toggle Synch Value
        unsigned char UOWN:1;                //USB Ownership
    };
    struct{
        unsigned char :1;
        unsigned char :1;
        unsigned char PID0:1;
        unsigned char PID1:1;
        unsigned char PID2:1;
        unsigned char PID3:1;
        unsigned char :1;
        unsigned char :1;
    };
    struct{
        unsigned char :2;
        unsigned char PID:4;                 //Packet Identifier
        unsigned char :2;
    };
} BD_STAT;                              //Buffer Descriptor Status Register

typedef union _BDT
{
    struct
    {
        BD_STAT Stat;
        byte Cnt;
        byte ADRL;                      //Buffer Address Low
        byte ADRH;                      //Buffer Address High
    };
    struct
    {
        unsigned char :8;
        unsigned char :8;
        word ADR;                      //Buffer Address
    };
} BDT;                                  //Buffer Descriptor Table

// E X T E R N S ************************************************************

extern byte usb_device_state;
extern USB_DEVICE_STATUS usb_stat;
extern byte usb_active_cfg;
extern byte usb_alt_intf[MAX_NUM_INT];
//extern byte epOutSize[MAX_EP_NUMBER];
//extern byte epInSize[MAX_EP_NUMBER];
extern const unsigned char ROM_MAX_EP_NUMBER;

extern volatile BDT ep0Bo;          //Endpoint #0 BD Out
extern volatile BDT ep0Bi;          //Endpoint #0 BD In
extern volatile BDT ep1Bo;          //Endpoint #1 BD Out
extern volatile BDT ep1Bi;          //Endpoint #1 BD In
extern volatile BDT ep2Bo;          //Endpoint #2 BD Out
extern volatile BDT ep2Bi;          //Endpoint #2 BD In
extern volatile BDT ep3Bo;          //Endpoint #3 BD Out
extern volatile BDT ep3Bi;          //Endpoint #3 BD In
extern volatile BDT ep4Bo;          //Endpoint #4 BD Out
extern volatile BDT ep4Bi;          //Endpoint #4 BD In
extern volatile BDT ep5Bo;          //Endpoint #5 BD Out
extern volatile BDT ep5Bi;          //Endpoint #5 BD In
extern volatile BDT ep6Bo;          //Endpoint #6 BD Out
extern volatile BDT ep6Bi;          //Endpoint #6 BD In
extern volatile BDT ep7Bo;          //Endpoint #7 BD Out
extern volatile BDT ep7Bi;          //Endpoint #7 BD In
extern volatile BDT ep8Bo;          //Endpoint #8 BD Out
extern volatile BDT ep8Bi;          //Endpoint #8 BD In
extern volatile BDT ep9Bo;          //Endpoint #9 BD Out
extern volatile BDT ep9Bi;          //Endpoint #9 BD In
extern volatile BDT ep10Bo;          //Endpoint #10 BD Out
extern volatile BDT ep10Bi;          //Endpoint #10 BD In
extern volatile BDT ep11Bo;          //Endpoint #11 BD Out
extern volatile BDT ep11Bi;          //Endpoint #11 BD In
extern volatile BDT ep12Bo;          //Endpoint #12 BD Out
extern volatile BDT ep12Bi;          //Endpoint #12 BD In
extern volatile BDT ep13Bo;          //Endpoint #13 BD Out
extern volatile BDT ep13Bi;          //Endpoint #13 BD In
extern volatile BDT ep14Bo;          //Endpoint #14 BD Out
extern volatile BDT ep14Bi;          //Endpoint #14 BD In
extern volatile BDT ep15Bo;          //Endpoint #15 BD Out
extern volatile BDT ep15Bi;          //Endpoint #15 BD In

extern volatile CTRL_TRF_SETUP SetupPkt;
extern volatile CTRL_TRF_DATA CtrlTrfData;

extern volatile byte ep1_out_buffer[USBGEN_EP_SIZE];
extern volatile byte ep1_in_buffer[USBGEN_EP_SIZE];
/*extern volatile byte ep2_out_buffer[USBGEN_EP_SIZE];
extern volatile byte ep2_in_buffer[USBGEN_EP_SIZE];
extern volatile byte ep3_out_buffer[USBGEN_EP_SIZE];
extern volatile byte ep3_in_buffer[USBGEN_EP_SIZE];*/
// P U B L I C  P R O T O T Y P E S *****************************************

void USBInitEPs(void);
#endif //USBMMAP_H